version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install -y git sudo ansible locales
      - checkout
      - run:
          name: Execute Ansible playbook
          command: ansible-playbook -i hosts site.yml
